# Generated by Django 5.2 on 2025-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de entrega"
                    ),
                ),
                ("deadline", models.DateField()),
                ("finished_at", models.DateField(null=True)),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
    ]
