# Generated by Django 5.2 on 2025-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
